server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cilicili?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc521521521
  jpa:
    open-in-view: false

#微信小程序appId
appId: wx18783a513dd8b26f
appSecret: a45f500599adaeb41de4ee22ace71084