server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-originPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          # 启用服务发现自动路由
          enabled: true
      routes:

        #用户服务路由
        - id: routes-account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**

        #上传服务路由
        - id: routes-upload-service
          uri: lb://upload-service
          predicates:
            - Path=/upload-service/**

        #邮件服务路由
        - id: routes-email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**

        #直播间服务路由
        - id: routes-room-service
          uri: lb://room-service
          predicates:
            - Path=/room-service/**

      #去除路由前缀
      default-filters:
        - StripPrefix=1